FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# OS deps minimales
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl ca-certificates libffi-dev libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copier uniquement les deps d'abord pour profiter du cache
COPY requirements.txt /app/

# Installer les deps Python
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout ton code
COPY . /app

# Port FastAPI
EXPOSE 8000

# Démarrage (production, pas de reload)
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers", "--forwarded-allow-ips=*"]
